# Generated by Django 4.0.3 on 2022-04-13 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancyfromstep', '0002_alter_vacancy_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'наименование компании', 'verbose_name_plural': 'список компаний'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'специальность', 'verbose_name_plural': 'список специальностей'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'вакансия', 'verbose_name_plural': 'лист вакансий'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateField(auto_now=True),
        ),
    ]
