# Generated by Django 4.0.3 on 2022-04-13 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancyfromstep', '0003_alter_company_options_alter_specialty_options_and_more'),
    ]

