# Generated by Django 4.0.3 on 2022-04-13 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancyfromstep', '0004_rezume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('status', models.CharField(choices=[('Не ищу работу', 'Not Find'), ('Рассматриваю предложения', 'Maybe'), ('Ищу работу', 'Find')], max_length=30, verbose_name='Готовность к работе')),
                ('salary', models.PositiveIntegerField(verbose_name='Вознаграждение')),
                ('grade', models.CharField(choices=[('Стажер', 'Stag'), ('Джуниор', 'Juni'), ('Миддл', 'Midd'), ('Синьор', 'Seni'), ('Лид', 'Lidd')], max_length=10, verbose_name='Квалификация')),
                ('education', models.CharField(max_length=20, verbose_name='Образование')),
                ('experience', models.CharField(max_length=100, verbose_name='Опыт работы')),
                ('portfolio', models.CharField(max_length=200, verbose_name='Портфолио')),
                ('published_at', models.DateField(auto_now=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezume', to='vacancyfromstep.specialty', verbose_name='Специализация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rezume', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'резюме пользователя',
                'verbose_name_plural': 'лист резюме',
            },
        ),
    ]
